// Code generated by "gofastr gen styles" from siteheader.tokens.css. DO NOT EDIT.
// Source hash: sha256:f2284a5f3997a250fb283984d3c76941420149f2f022193f4876eab9c041b251

package siteheader

import (
	"time"

	"github.com/DonaldMurillo/gofastr/core-ui/style"
)

// Tokens is siteheader.tokens.css as typed theme tokens. Add them to the theme with
// Extend, which also takes the file's dark values:
//
//	site.WithTheme(theme.Default().Extend(siteheader.Tokens))
var Tokens = siteheaderTokens{
	Durations: siteheaderDurations{
		MenuStagger: style.Duration{Name: "menu-stagger", Value: 40 * time.Millisecond},
	},
}

// siteheaderTokens is the token set of siteheader.tokens.css, grouped like style.Theme.
type siteheaderTokens struct {
	Durations siteheaderDurations
}

// siteheaderDurations are the style.Duration tokens of siteheader.tokens.css.
type siteheaderDurations struct {
	// MenuStagger is --duration-menu-stagger. The phone menu's rows land one after another, each this much after
	// the one above; the call to action follows the last row.
	MenuStagger style.Duration
}
