// User-journey e2e for the scanner plugin — the plugin whose input is a device.
//
// The claim under test is a negative one made useful: the camera is unreachable
// from an opaque-origin frame (getUserMedia fails there with SecurityError, and
// allow="camera" does not change it — measured, see #19), so the HOST captures
// and the cage decodes. These journeys assert both halves: pixels reach the
// frame from three different sources, and the frame still opens no connection
// of its own.
import { test, expect, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const PORT = Number(process.env.E2E_PORT ?? 8123);
const DEMO = `http://localhost:${PORT}/scanner`;

// The committed fixture and the payload it carries. Generated by
// scanner/js/scripts/gen-qr-fixture.mjs, which asserts the round trip before
// writing — a fixture that does not decode cannot be committed.
const FIXTURE = join(__dirname, "..", "fixtures", "sample-qr.png");
const FIXTURE_TEXT = "GOFASTR-SCAN-OK";

type Mirror = HTMLIFrameElement & {
  __scannerReady?: boolean;
  __scannerCameraState?: "idle" | "live" | "denied" | "unsupported";
  __scannerFramesSent?: number;
  __scannerStats?: { framesSeen: number; decodes: number; lastDecodeMs: number; lastText: string };
  __scannerLastResult?: { text: string; format: string; via: "native" | "zxing"; decodeMs: number };
  __scannerProbes?: { cookieEmpty: boolean; parentBlocked: boolean; storageBlocked: boolean };
};

declare global {
  interface Window {
    __gofastrScannerDemo?: {
      startCamera(): Promise<void>;
      stopCamera(): void;
      scanSample(): Promise<void>;
      scanImageFile(file: File | Blob): Promise<void>;
      forceDecoder(which: "native" | "zxing" | "auto"): void;
      decoderAvailability(): { native: boolean; zxing: boolean };
      lastResult(): { text: string; format: string; via: string } | null;
    };
  }
}

const consoleErrors = new Map<Page, string[]>();

test.beforeEach(async ({ page }) => {
  const errors: string[] = [];
  consoleErrors.set(page, errors);
  page.on("console", (m) => {
    if (m.type() === "error") errors.push(m.text());
  });
  page.on("pageerror", (e) => errors.push(String(e)));
  await page.goto(DEMO);
  await page.waitForFunction(
    () => (document.querySelector(".editor-card iframe") as Mirror | null)?.__scannerReady === true,
    undefined,
    { timeout: 20_000 }
  );
  // The mount sits under a hero; Playwright cannot scroll an element that lives
  // INSIDE the iframe into view, so bring the frame itself in first (#25).
  await page.locator(".editor-card").scrollIntoViewIfNeeded();
});

function expectNoConsoleErrors(page: Page): void {
  const errors = (consoleErrors.get(page) ?? []).filter((e) => !/favicon/i.test(e));
  expect(errors, errors.join("\n")).toEqual([]);
}

async function lastResult(page: Page) {
  return page.evaluate(() => {
    const f = document.querySelector(".editor-card iframe") as Mirror | null;
    return f?.__scannerLastResult ?? null;
  });
}

// ─── 1. mount + sandbox + isolation probes ──────────────────────────────────

test("mounts sandboxed (allow-scripts, no allow-same-origin) with the frame's own isolation probes passing", async ({ page }) => {
  const frame = page.locator(".editor-card iframe");
  await expect(frame).toHaveAttribute("sandbox", "allow-scripts");
  await expect(frame).toHaveAttribute("referrerpolicy", "no-referrer");

  const probes = await page.evaluate(() => {
    const f = document.querySelector(".editor-card iframe") as Mirror;
    return f.__scannerProbes ?? {};
  });
  expect(probes).toEqual({ cookieEmpty: true, parentBlocked: true, storageBlocked: true });

  expectNoConsoleErrors(page);
});

// ─── 2. the sample decodes, with no camera and no image asset ───────────────

test("the built-in sample decodes: the page demonstrates itself with no camera", async ({ page }) => {
  await page.locator("#scan-sample").click();
  await expect
    .poll(async () => (await lastResult(page))?.text, { timeout: 15_000, message: "sample never decoded" })
    .toBeTruthy();

  const res = (await lastResult(page))!;
  expect(res.format).toBe("QR_CODE");
  expect(res.text.length).toBeGreaterThan(0);
  // The page must SHOW it, not merely mirror it.
  await expect(page.locator("#scan-result")).toContainText(res.text);

  expectNoConsoleErrors(page);
});

// ─── 3. a real image file crosses the bridge and decodes ────────────────────

test("an uploaded image decodes: host reads the pixels, the cage reads the code", async ({ page }) => {
  await page.setInputFiles("#scan-file", FIXTURE);

  await expect
    .poll(async () => (await lastResult(page))?.text, { timeout: 15_000, message: "the fixture never decoded" })
    .toBe(FIXTURE_TEXT);

  const res = (await lastResult(page))!;
  expect(res.format).toBe("QR_CODE");
  expect(res.decodeMs).toBeLessThan(2_000);

  // The frame received pixels; the host sent them. Both counters must move, or
  // something short-circuited the bridge and decoded on the host side.
  // The stats mirror is throttled to one event per 500ms, so it can legitimately
  // trail the result that arrived on its own event. Poll rather than snapshot.
  await expect
    .poll(
      async () =>
        page.evaluate(() => {
          const f = document.querySelector(".editor-card iframe") as Mirror | null;
          return f?.__scannerStats?.framesSeen ?? 0;
        }),
      { timeout: 10_000, message: "the frame never reported seeing a frame" }
    )
    .toBeGreaterThan(0);

  const sent = await page.evaluate(() => {
    const f = document.querySelector(".editor-card iframe") as Mirror | null;
    return { framesSent: f?.__scannerFramesSent ?? 0, framesSeen: f?.__scannerStats?.framesSeen ?? 0 };
  });
  expect(sent.framesSent, "the host never sent a frame").toBeGreaterThan(0);
  expect(sent.framesSeen, "the frame never reported seeing one").toBeGreaterThan(0);

  expectNoConsoleErrors(page);
});

// ─── 4. BOTH decoder paths, forced ──────────────────────────────────────────

test("both decoders read the same code: the native one and the bundled fallback", async ({ page }) => {
  // Whichever decoder the runner happens to have would otherwise be the only one
  // ever exercised — CI's Linux chromium has no BarcodeDetector, a mac has one —
  // so each path would rot on the machine that never runs it. Force both.
  //
  // The ordering matters for a reason worth keeping: zxing's decoder fails on
  // some valid QR codes its own encoder produces (#19), so native is preferred
  // where it exists and this test is what keeps the fallback honest.
  const avail = await page.evaluate(() => window.__gofastrScannerDemo!.decoderAvailability());

  for (const which of ["zxing", "native"] as const) {
    if (which === "native" && !avail.native) {
      test.info().annotations.push({ type: "skip-path", description: "no BarcodeDetector on this engine" });
      continue;
    }
    await page.evaluate((w) => window.__gofastrScannerDemo!.forceDecoder(w), which);
    await page.setInputFiles("#scan-file", []);
    await page.setInputFiles("#scan-file", FIXTURE);

    await expect
      .poll(async () => (await lastResult(page))?.via === which && (await lastResult(page))?.text, {
        timeout: 15_000,
        message: `the ${which} decoder never produced a result`,
      })
      .toBe(FIXTURE_TEXT);
  }

  expectNoConsoleErrors(page);
});

// ─── 5. no camera is a state, not a crash ───────────────────────────────────

test("a refused camera is a state the page renders, not an error it throws", async ({ page, context }) => {
  await context.clearPermissions(); // deny by default
  // Fire and forget: on an engine with no camera at all, startCamera's promise
  // may never settle, and awaiting it inside evaluate would hang the test
  // rather than test anything.
  await page.evaluate(() => {
    void window.__gofastrScannerDemo!.startCamera().catch(() => {});
  });

  await expect
    .poll(
      async () =>
        page.evaluate(() => (document.querySelector(".editor-card iframe") as Mirror | null)?.__scannerCameraState),
      { timeout: 15_000, message: "camera state never left idle" }
    )
    .not.toBe("live");

  const state = await page.evaluate(
    () => (document.querySelector(".editor-card iframe") as Mirror | null)?.__scannerCameraState
  );
  expect(["denied", "unsupported", "idle"]).toContain(state);
  // Whatever happened, the page says so rather than sitting silent.
  await expect(page.locator("#scan-camera-state")).not.toBeEmpty();

  // A refused camera must not stop the plugin working from other sources.
  await page.setInputFiles("#scan-file", FIXTURE);
  await expect
    .poll(async () => (await lastResult(page))?.text, { timeout: 15_000 })
    .toBe(FIXTURE_TEXT);

  expectNoConsoleErrors(page);
});

// ─── 6. the frame opens nothing of its own ──────────────────────────────────

test("across a full scan session the frame issues zero network requests", async ({ page }) => {
  const framedRequests: string[] = [];
  page.on("request", (req) => {
    const frame = req.frame();
    if (frame && frame !== page.mainFrame()) framedRequests.push(`${req.method()} ${req.url()}`);
  });

  await page.locator("#scan-sample").click();
  await expect.poll(async () => (await lastResult(page))?.text, { timeout: 15_000 }).toBeTruthy();
  await page.setInputFiles("#scan-file", FIXTURE);
  await expect.poll(async () => (await lastResult(page))?.text, { timeout: 15_000 }).toBe(FIXTURE_TEXT);

  // The frame's own document and bundle are fetched by the HOST navigation, so
  // only requests the frame ITSELF initiates count — and there must be none.
  const initiated = framedRequests.filter((r) => !/\/__gofastr\/plugin\/scanner\/(frame\.html|scan\.(js|css))/.test(r));
  expect(initiated, initiated.join("\n")).toEqual([]);

  expectNoConsoleErrors(page);
});
