package pdf

import (
	"embed"
	"io/fs"
)

// assets holds the prebuilt frame artifacts produced by `npm run build` in
// pdf/js (viewer.html / viewer.js / viewer.css) plus the SPIKE sample PDF
// produced by `npm run gen-sample`. The Go plugin go:embed's them and serves
// them same-origin via pluginhost.AssetServer.
//
//go:embed assets
var assetsFS embed.FS

//go:embed host/adapter.js
var adapterJSBytes []byte

// framedAssets returns the embedded frame assets sub-tree. AssetServer serves
// each spec under RoutePrefix with the framed CSP/CORP relaxation.
func framedAssets() fs.FS {
	sub, err := fs.Sub(assetsFS, "assets")
	if err != nil {
		panic("pdf: embed assets sub: " + err.Error())
	}
	return sub
}

//go:embed assets/sample.pdf
var samplePDF embed.FS

// samplePDFBytes returns the SPIKE sample PDF (generated by pdf/js `npm run
// gen-sample`). Served at SamplePDFURL for the host adapter to fetch same-origin
// and forward over the bridge.
func samplePDFBytes() []byte {
	b, err := samplePDF.ReadFile("assets/sample.pdf")
	if err != nil {
		panic("pdf: embed sample.pdf: " + err.Error())
	}
	return b
}
