// Code generated by "gofastr gen styles" from sitefooter.style.css. DO NOT EDIT.
// Source hash: sha256:c865d7626fa19ab00a1c10e5372c148bbc20694f9605c0f7f392afe3ecb85021

package sitefooter

import "github.com/DonaldMurillo/gofastr/core-ui/ownstyle"

// sitefooterCSS is the checked source of the sitefooter owned style.
const sitefooterCSS = `/* The app's colophon: the name and a line about the app, then the
   link columns, over a quiet bottom line. The content sits on the page
   measure (--size-page-width, with --size-page-gutter outside it), the
   column the header and main use. */
:scope {
  border-block-start: 1px solid var(--color-border);
}

.inner {
  max-inline-size: calc(var(--size-page-width) + 2 * var(--size-page-gutter));
  margin-inline: auto;
  padding: var(--spacing-3xl) var(--size-page-gutter) var(--spacing-xl);
}

/* The lead takes the first third; the columns share the rest and wrap
   when they run out of room. */
.top {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 2fr);
  gap: var(--spacing-2xl);
}

.brand {
  color: var(--color-text);
  font-weight: var(--font-weight-semibold);
  text-decoration: none;
}
.tagline {
  margin: var(--spacing-md) 0 0;
  max-inline-size: 32ch;
  color: var(--color-text-muted);
  font-size: var(--text-sm);
  line-height: 1.6;
}

.columns {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(8rem, 1fr));
  gap: var(--spacing-xl);
}
.title {
  margin: 0 0 var(--spacing-md);
  color: var(--color-text);
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
}
.links {
  display: grid;
  gap: var(--spacing-md);
  margin: 0;
  padding: 0;
  list-style: none;
}
.links a {
  color: var(--color-text-muted);
  font-size: var(--text-sm);
  text-decoration: none;
  transition: color var(--duration-fast) var(--easing-ease-out);
}
.links a:hover { color: var(--color-text); }
.links a:focus-visible,
.brand:focus-visible { outline: 2px solid var(--color-primary); outline-offset: 2px; }

.note {
  margin: var(--spacing-2xl) 0 0;
  padding-block-start: var(--spacing-lg);
  border-block-start: 1px solid var(--color-border);
  color: var(--color-text-subtle);
  font-size: var(--text-xs);
}

@media (--reduced-motion) {
  .links a { transition: none; }
}

/* Phones: the lead stacks over the columns. */
@media (--below-md) {
  .top { grid-template-columns: minmax(0, 1fr); }
}
`

// sitefooterStyle carries the sitefooter owned style: the registered sheet (Name, Kind and
// Scope come from the embedded *ownstyle.Sheet) plus its class
// vocabulary as methods returning local class names.
type sitefooterStyle struct {
	*ownstyle.Sheet
}

// Style is the sitefooter owned style, registered at init.
// This package holds exactly one style file, so the handle is
// exported as Style; a package holding several exports each as
// <Owner>Style.
var Style = sitefooterStyle{ownstyle.Must("sitefooter", ownstyle.KindScoped, sitefooterCSS)}

// Inner returns the local class name "inner".
func (s sitefooterStyle) Inner() string { return "inner" }

// Top returns the local class name "top".
//
// The lead takes the first third; the columns share the rest and wrap
// when they run out of room.
func (s sitefooterStyle) Top() string { return "top" }

// Brand returns the local class name "brand".
func (s sitefooterStyle) Brand() string { return "brand" }

// Tagline returns the local class name "tagline".
func (s sitefooterStyle) Tagline() string { return "tagline" }

// Columns returns the local class name "columns".
func (s sitefooterStyle) Columns() string { return "columns" }

// Title returns the local class name "title".
func (s sitefooterStyle) Title() string { return "title" }

// Links returns the local class name "links".
func (s sitefooterStyle) Links() string { return "links" }

// Note returns the local class name "note".
func (s sitefooterStyle) Note() string { return "note" }
