package ssr

// d3-array tick port — DO NOT "fix" this file.
//
// This is a line-for-line port of d3-array 3.2.4's ticks/tickIncrement/
// tickStep (https://cdn.jsdelivr.net/npm/d3-array@3.2.4/src/ticks.js):
//
//	const e10 = Math.sqrt(50), e5 = Math.sqrt(10), e2 = Math.sqrt(2);
//	function tickSpec(start, stop, count) {
//	  const step = (stop - start) / Math.max(0, count),
//	      power = Math.floor(Math.log10(step)),
//	      error = step / Math.pow(10, power),
//	      factor = error >= e10 ? 10 : error >= e5 ? 5 : error >= e2 ? 2 : 1;
//	  let i1, i2, inc;
//	  if (power < 0) {
//	    inc = Math.pow(10, -power) / factor;
//	    i1 = Math.round(start * inc);
//	    i2 = Math.round(stop * inc);
//	    if (i1 / inc < start) ++i1;
//	    if (i2 / inc > stop) --i2;
//	    inc = -inc;
//	  } else {
//	    inc = Math.pow(10, power) * factor;
//	    i1 = Math.round(start / inc);
//	    i2 = Math.round(stop / inc);
//	    if (i1 * inc < start) ++i1;
//	    if (i2 * inc > stop) --i2;
//	  }
//	  if (i2 < i1 && 0.5 <= count && count < 2) return tickSpec(start, stop, count * 2);
//	  return [i1, i2, inc];
//	}
//	export default function ticks(start, stop, count) { ... }
//	export function tickIncrement(start, stop, count) { ... }
//	export function tickStep(start, stop, count) { ... }
//
// Observable Plot's axes sample ticks through d3-scale's linear.ticks, which
// calls exactly `ticks(domain[0], domain[domain.length-1], count)`. The frame
// bundle runs the real d3; this port is what the server SVG runs. If the two
// disagree on axis labels for perfectly ordinary data, the plugin is
// worthless — so the algorithm is ported faithfully (including the reverse
// branch and the count<2 doubling recursion), NOT reinvented as a generic
// nice-number pass.
//
// Fidelity notes:
//   - All arithmetic stays in float64 because the reference is IEEE-754
//     doubles in JS; converting the integer indices i1/i2 to Go ints would
//     change rounding for huge magnitudes.
//   - jsRound mirrors JS Math.round (half UP, toward +Infinity), which is
//     NOT Go's math.Round (half away from zero): Math.round(-2.5) === -2.
//   - Fidelity is enforced by test: ticks_test.go replays a committed
//     ground-truth sweep generated by real d3-array in Node (see
//     testdata/d3ticks.json) and fails on any float or label mismatch.

import (
	"math"
	"strconv"
)

var (
	e10 = math.Sqrt(50)
	e5  = math.Sqrt(10)
	e2  = math.Sqrt(2)
)

// jsRound rounds half toward +Infinity, exactly like JS Math.round.
func jsRound(x float64) float64 { return math.Floor(x + 0.5) }

// tickSpec is the shared core of d3-array's ticks/tickIncrement/tickStep.
func tickSpec(start, stop float64, count float64) (i1, i2, inc float64) {
	step := (stop - start) / math.Max(0, count)
	power := math.Floor(math.Log10(step))
	err := step / math.Pow(10, power)
	factor := 1.0
	switch {
	case err >= e10:
		factor = 10
	case err >= e5:
		factor = 5
	case err >= e2:
		factor = 2
	}
	if power < 0 {
		inc = math.Pow(10, -power) / factor
		i1 = jsRound(start * inc)
		i2 = jsRound(stop * inc)
		if i1/inc < start {
			i1++
		}
		if i2/inc > stop {
			i2--
		}
		inc = -inc
	} else {
		inc = math.Pow(10, power) * factor
		i1 = jsRound(start / inc)
		i2 = jsRound(stop / inc)
		if i1*inc < start {
			i1++
		}
		if i2*inc > stop {
			i2--
		}
	}
	if i2 < i1 && 0.5 <= count && count < 2 {
		return tickSpec(start, stop, count*2)
	}
	return i1, i2, inc
}

// Ticks port d3-array's ticks(start, stop, count). count is a float64
// because d3's is (the count<2 doubling branch compares fractional
// counts); renderers pass integers. Inputs must be finite; non-finite
// input or a count <= 0 yields nil (empty), as in JS.
func Ticks(start, stop, count float64) []float64 {
	c := count
	if !(c > 0) || math.IsNaN(start) || math.IsNaN(stop) ||
		math.IsInf(start, 0) || math.IsInf(stop, 0) {
		return nil
	}
	if start == stop {
		return []float64{start}
	}
	reverse := stop < start
	lo, hi := start, stop
	if reverse {
		lo, hi = stop, start
	}
	i1, i2, inc := tickSpec(lo, hi, c)
	if !(i2 >= i1) {
		return nil
	}
	n := int(i2 - i1 + 1)
	out := make([]float64, n)
	if inc < 0 {
		for i := range n {
			out[i] = (i1 + float64(i)) / -inc
		}
	} else {
		for i := range n {
			out[i] = (i1 + float64(i)) * inc
		}
	}
	if reverse {
		for i, j := 0, n-1; i < j; i, j = i+1, j-1 {
			out[i], out[j] = out[j], out[i]
		}
	}
	return out
}

// TickIncrement ports d3-array's tickIncrement (the raw inc, which is
// negative for sub-unit steps).
func TickIncrement(start, stop, count float64) float64 {
	_, _, inc := tickSpec(start, stop, count)
	return inc
}

// TickStep ports d3-array's tickStep: a positive (or negative, when stop <
// start) step magnitude.
func TickStep(start, stop, count float64) float64 {
	reverse := stop < start
	lo, hi := start, stop
	if reverse {
		lo, hi = stop, start
	}
	inc := TickIncrement(lo, hi, count)
	sign := 1.0
	if reverse {
		sign = -1
	}
	if inc < 0 {
		return sign * (1 / -inc)
	}
	return sign * inc
}

// tickStepLabelPrecision returns the number of fraction digits used to
// format tick labels for a given positive step. The frame bundle computes
// the same quantity ("smallest p such that formatting the step with p
// decimals round-trips to the same double"), which is engine-independent —
// Math.log10-based derivations can differ between JS engines and Go's
// math.Log10 at exact power-of-ten boundaries. Verified equivalent to d3's
// precisionFixed over the committed ground-truth sweep.
func tickStepLabelPrecision(step float64) int {
	if !(step > 0) || math.IsInf(step, 0) || math.IsNaN(step) {
		return 0
	}
	for p := 0; p <= 17; p++ {
		if s := strconv.FormatFloat(step, 'f', p, 64); mustParseFloat(s) == step {
			return p
		}
	}
	return 17
}

// mustParseFloat parses what strconv.FormatFloat produced with 'f'; it
// never fails for those strings, and NaN on any impossible input keeps the
// comparison above false rather than panicking.
func mustParseFloat(s string) float64 {
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return math.NaN()
	}
	return v
}

// FormatFloatFixed formats v with p fraction digits, matching JS
// Number.prototype.toFixed for the values ticks produce (multiples of
// 1/2/5 × 10^k, which are exact at their step precision, so no tie-breaking
// divergence arises). The one real divergence is negative zero: JS
// (-0).toFixed(1) === "0.0", Go prints "-0.0" — normalized here.
func FormatFloatFixed(v float64, p int) string {
	if v == 0 {
		v = 0 // normalize -0
	}
	return strconv.FormatFloat(v, 'f', p, 64)
}

// TickLabels returns the axis tick label strings for a domain and count —
// the exact strings the hydrated Plot chart shows. This is the surface the
// server/client agreement test compares.
func TickLabels(domain [2]float64, count int) []string {
	c := float64(count)
	ts := Ticks(domain[0], domain[1], c)
	if ts == nil {
		return nil
	}
	step := TickStep(domain[0], domain[1], c)
	p := tickStepLabelPrecision(step)
	out := make([]string, len(ts))
	for i, v := range ts {
		out[i] = FormatFloatFixed(v, p)
	}
	return out
}
