// Code generated by "gofastr gen styles" from docpage.tokens.css. DO NOT EDIT.
// Source hash: sha256:8e700f6e14116478a9b3b54575271de94033c13f99b005f1e3d181679c9ca63b

package docpage

import "github.com/DonaldMurillo/gofastr/core-ui/style"

// Tokens is docpage.tokens.css as typed theme tokens. Add them to the theme with
// Extend, which also takes the file's dark values:
//
//	site.WithTheme(theme.Default().Extend(docpage.Tokens))
var Tokens = docpageTokens{
	Sizes: docpageSizes{
		ProseMeasure: style.Size{Name: "prose-measure", Value: "68ch"},
	},
}

// docpageTokens is the token set of docpage.tokens.css, grouped like style.Theme.
type docpageTokens struct {
	Sizes docpageSizes
}

// docpageSizes are the style.Size tokens of docpage.tokens.css.
type docpageSizes struct {
	// ProseMeasure is --size-prose-measure. The longest line an article's text runs to.
	ProseMeasure style.Size
}
